# NB: don't set `language: haskell` here

# See also https://github.com/hvr/multi-ghc-travis for more information

env:
  - CABALVER=1.22 GHCVER=7.8.4

# Note: the distinction between `before_install` and `install` is not
#       important.

install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - cabal --version
  - ghc --version
  - travis_retry cabal update
  - cabal install --only-dependencies

# Here starts the actual work to be performed for the package under
# test; any command which exits with a non-zero exit code causes the
# build to fail.

script:
  - cabal configure -v2
  - cabal build -v2
  - cabal install

# Branches to test
branches:
  only:
    - master
